language: node_js
node_js:
- node
cache:
  directories:
  - "~/.npm"
  - "~/.cache"
script:
- npm run lint
- npm run test
deploy:
  provider: heroku
  api_key:
    secure: Sgs6SfN0dLyM2D/MPqMzGTnYmBgckRO32xyb9A8FlwrPwRHZFuXNEIDTWOmOb9bgi2BzGvsNUdzsAVmsNPxQl82m9yXxe5i1mKmGzL7EXdOS5qX1D034DAEzDMRaHUuC0YForCYZHyvNXRqZime5v/Z6x0kKcxfmZYePKvtEmTHAAxzEcCxzdT28qZSwLjxGr+v4PhnNPdlZymYZkZv+oO+YT6HYRJvtH9MMoAYDDVE9n8EBfBnAkcbY9QQ+03ClGVEdRjQea2l+DW5xAsO8PRlYPV83JfDPb0nQBwskC+tU0TDEUlt0RPbai/SvwPDakoY7mFaFTW01wSQhp4EllaUcKiGdLr9LWQQ3O7eMXJmEj5h5hWluc/02SMdJiLD9dkdPJULYz1K2PXZslXKP3tphVXW+z5oUmYh3dDGq8xmkNnsqqVe/21pedFyRBnxO0NB0fsEtpENjitpYEnhDPP9ZxYBH4ixPOxnkVgr0m/p4RbvXZCExN760aFsqam8WX9DxMb6rt8b8MWoLxcBQ05bVeK8RAIYaIBkH1j5SZ5KlZZzyr1ZadAUYyeN7y02VYSgCAerpDgCFee7IkAiJHK4I8e9ZLamEatj0+S9CEM3muDajToTXmr8gN6Kxyrju6wuX8WQxJTH/J5gL3o6ttOmrdqQdjH55UVCO1xpc6vs=
  app:
    dev: exercise-contacts
